K22CNT3_DoKhacViet_Project2/K22CNT3_DoKhacViet_Project2/Controllers/DKVCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using K22CNT3_DoKhacViet_Project2.Models;
using K22CNT3_DoKhacViet_Project2.Bussiness;

namespace K22CNT3_DoKhacViet_Project2.Controllers
{
    public class DKVCartController : Controller
    {
        private const string DKVCartSessionKey = "DKVCartSessionKey";
        DKVDbEntities dbEntities = new DKVDbEntities();

        private DKV_ShoppingCart GetCart()
        {
            var cart = Session[DKVCartSessionKey] as DKV_ShoppingCart;
            if (cart == null)
            {
                cart = new DKV_ShoppingCart();
                Session[DKVCartSessionKey] = cart;
            }

            return cart;
        }

        // Add to cart: them mot san pham vao gio hang
        public ActionResult AddToCart(int id, string TenHinhNen, String HinhAnh, int SoLuongMua, float DonGiaMua)
        {
            var cart = GetCart();
            var item = new DKVCartItem
            {
                ID = id,
                TenHinhNen = TenHinhNen,
                HinhAnh = HinhAnh,
                SoLuongMua = SoLuongMua,
                DonGiaMua = DonGiaMua,
                ThanhTien = SoLuongMua * DonGiaMua
            };

            cart.AddToCart(item);
            return RedirectToAction("Index");

        }

        // GET: DVHCart - Hiển thị các sản phẩm trong giỏ hàng
        public ActionResult Index()
        {
            var cart = GetCart();
            return View(cart.Items);
        }

        // Trang thong tin thanh toan
        public ActionResult ThongTinThanhToan()
        {
            var cart = GetCart();
            ViewBag.TongTriGia = cart.GetTongThanhTien();
            DateTime dt = DateTime.Now;
            var MaHoaDon = "DH-" + dt.ToString("yyyyMMdd-HHmmss");
            ViewBag.MaHoaDon = MaHoaDon;
            return View(cart.Items);
        }

        // Cập nhật và thanh toán
        public ActionResult ThanhToan(FormCollection form)
        {
            var cart = GetCart();

            // Lấy các thông tin trên form để cập nhật bảng hóa đơn
            var HoTenKhachHang = form["HoTenKhachHang"];
            var Email = form["Email"];
            var DienThoai = form["DienThoai"];
            var DiaChi = form["DiaChi"];

            // Thông tin đơn hàng
            DateTime dt = DateTime.Now;
            var MaHoaDon = "DH-" + dt.ToString("yyyyMMdd-HHmmss");
            var NgayNhan = form["NgayNhan"];
            var TriGia = cart.GetTongThanhTien();

            // Thêm mới vào bảng HoaDon
            var hoaDon = new HOA_DON();
            hoaDon.MaHoaDon = MaHoaDon;
            hoaDon.MaKhachHang = 1;
            hoaDon.NgayHoaDon = dt;
            hoaDon.NgayNhan = DateTime.Parse(NgayNhan);
            hoaDon.TongTriGia = TriGia;
            hoaDon.HoTenKhachHang = HoTenKhachHang;
            hoaDon.Email = Email;
            hoaDon.DienThoai = DienThoai;
            hoaDon.DiaChi = DiaChi;
            hoaDon.TrangThai = 0;

            dbEntities.HOA_DON.Add(hoaDon);
            dbEntities.SaveChanges();

            // Lấy id hóa đơn vừa thêm
            int hoaDonId = dbEntities.HOA_DON.Max(x => x.ID);

            // Thêm vào chi tiết hóa đơn
            foreach (var item in cart.Items)
            {
                CT_HOA_DON ct = new CT_HOA_DON();
                ct.HoaDonID = hoaDonId;
                ct.SanPhamID = item.ID;
                ct.SoLuongMua = item.SoLuongMua;
                ct.DonGiaMua = item.DonGiaMua;
                ct.ThanhTien = item.ThanhTien;

                dbEntities.CT_HOA_DON.Add(ct);
                dbEntities.SaveChanges();
            }

            return RedirectToAction("CamOn");
        }

        public ActionResult CamOn()
        {
            return View();
        }

        // Cập nhật giỏ hàng
        public ActionResult UpdateFromCart(FormCollection form)
        {
            var cart = GetCart();
            var ids = form["ID"].Split(',');
            var qtys = form["SoLuongMua"].Split(',');
            for (int i = 0; i < ids.Length; i++)
            {
                int id = int.Parse(ids[i]);
                int qty = int.Parse(qtys[i]);
                cart.UpdateFromCart(id, qty);
            }
            return RedirectToAction("Index");
        }

        // Cập nhật một sản phẩm trong giỏ hàng
        public ActionResult UpdateItemCart(int id, int qty)
        {
            var cart = GetCart();
            cart.UpdateFromCart(id, qty);
            return RedirectToAction("Index");
        }

        // Xóa sản phẩm trong giỏ hàng
        public ActionResult DeleteItemCart(int id)
        {
            var cart = GetCart();
            cart.RemoveCartItem(id);
            return RedirectToAction("Index");
        }
    }
}

K22CNT3_DoKhacViet_Project2/K22CNT3_DoKhacViet_Project2/Controllers/DKV_HINH_NENController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT3_DoKhacViet_Project2.Models;

namespace K22CNT3_DoKhacViet_Project2.Controllers
{
    public class DKV_HINH_NENController : Controller
    {
        private DKVDbEntities db = new DKVDbEntities();

        // GET: DKV_HINH_NEN
        public ActionResult Index()
        {
            var hINH_NEN = db.HINH_NEN.Include(h => h.LOAI_HINH_NEN);
            return View(hINH_NEN.ToList());
        }

        // GET: DKV_HINH_NEN/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HINH_NEN hINH_NEN = db.HINH_NEN.Find(id);
            if (hINH_NEN == null)
            {
                return HttpNotFound();
            }
            return View(hINH_NEN);
        }

        // GET: DKV_HINH_NEN/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LOAI_HINH_NEN, "ID", "MaLoai");
            return View();
        }

        // POST: DKV_HINH_NEN/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,MaHinhNen,TenHinhNen,HinhAnh,SoLuong,DonGia,MaLoai,TrangThai")] HINH_NEN hINH_NEN)
        {
            if (ModelState.IsValid)
            {
                db.HINH_NEN.Add(hINH_NEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoai = new SelectList(db.LOAI_HINH_NEN, "ID", "MaLoai", hINH_NEN.MaLoai);
            return View(hINH_NEN);
        }

        // GET: DKV_HINH_NEN/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HINH_NEN hINH_NEN = db.HINH_NEN.Find(id);
            if (hINH_NEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoai = new SelectList(db.LOAI_HINH_NEN, "ID", "MaLoai", hINH_NEN.MaLoai);
            return View(hINH_NEN);
        }

        // POST: DKV_HINH_NEN/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,MaHinhNen,TenHinhNen,HinhAnh,SoLuong,DonGia,MaLoai,TrangThai")] HINH_NEN hINH_NEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hINH_NEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoai = new SelectList(db.LOAI_HINH_NEN, "ID", "MaLoai", hINH_NEN.MaLoai);
            return View(hINH_NEN);
        }

        // GET: DKV_HINH_NEN/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HINH_NEN hINH_NEN = db.HINH_NEN.Find(id);
            if (hINH_NEN == null)
            {
                return HttpNotFound();
            }
            return View(hINH_NEN);
        }

        // POST: DKV_HINH_NEN/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HINH_NEN hINH_NEN = db.HINH_NEN.Find(id);
            db.HINH_NEN.Remove(hINH_NEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

K22CNT3_DoKhacViet_Project2/K22CNT3_DoKhacViet_Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - K22CNT3 - Do Khac Viet - Project2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQX6sAXnS6O0o5U84xzl+KQf0Xz+eG0oOZlCeTv7TkTzrc0HX18hA5dXa" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .card {
            margin-bottom: 20px;
        }

        .card-img-top {
            width: 100%;
            height: 300px;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            @Html.ActionLink("Do Khac Viet", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Loai Hinh Nen", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Hinh Nen", "Index", "DKV_HINH_NEN", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Gio hang", "Index", "DKVCart", null, new { @class = "nav-link" })</li>
                </ul>
                <form class="d-flex me-2" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div class="d-flex">
                    <a href="#" class="btn btn-primary mx-1">Dang ky</a>
                    <a href="#" class="btn btn-success">Dang nhap</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content" style="margin-top: 80px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Do Khac Viet</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>